CREATE OR REPLACE PROCEDURE INSERT_CONTACT (nNAME IN VARCHAR2, lLAST_NAME IN VARCHAR2, aADRESSBOOK IN VARCHAR2, uUSERADDRESS IN VARCHAR2, pPASSWORD IN VARCHAR2)
IS
    cnt NUMBER;
BEGIN
    SELECT MAX(ID)
    INTO cnt
    FROM CONTACTS;

    INSERT INTO MAILADDRESSES(ADDRESS)
    VALUES(uUSERADDRESS);

    INSERT INTO USERS(ID, FIRSTNAME, SECONDNAME, ADDRESS, PASSWORD)
    VALUES(cnt+1, nNAME, lLAST_NAME, uUSERADDRESS, pPASSWORD);

    INSERT INTO ADDRESSBOOKS(NAME, USERADDRESS)
    VALUES(aADRESSBOOK, uUSERADDRESS);

    INSERT INTO CONTACTS (ID, NAME, ADRESSBOOK, USERADDRESS)
    VALUES(cnt+1, nNAME||lLAST_NAME, aADRESSBOOK, uUSERADDRESS);

END;
/
EXECUTE INSERT_CONTACT('Andrey', 'Sokolov', 'ADB3', 'andysok02@gmail.com', '54321');
