CREATE OR REPLACE PROCEDURE DELETE_CONTACT(nNAME IN VARCHAR2, lLAST_NAME IN VARCHAR2, uUSERADDRESS IN VARCHAR2)
    IS
        ID_ID NUMBER;

        CURSOR P1 IS
        SELECT UU.ID FROM USERS UU
        WHERE UU.FIRSTNAME LIKE nNAME AND UU.SECONDNAME LIKE lLAST_NAME AND UU.ADDRESS LIKE uUSERADDRESS;

BEGIN
    OPEN P1;
    FETCH P1 INTO ID_ID;

    DELETE FROM CONTACTS CC
    WHERE CC.ID = ID_ID;
    DELETE FROM ADDRESSBOOKS CC
    WHERE CC.USERADDRESS = uUSERADDRESS;
    DELETE FROM USERS CC
    WHERE CC.ID = ID_ID;
    DELETE FROM MAILADDRESSES CC
    WHERE CC.ADDRESS = uUSERADDRESS;

END;
/
EXECUTE DELETE_CONTACT('Andrey', 'Sokolov', 'andysok02@gmail.com');
